#- name: Enable add-ons
#  shell: |
#    sudo microk8s enable dns:/etc/resolv.conf registry storage ingress helm3

- name: Enable Sealed secret controller
  shell: |
    sudo microk8s.helm3 repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets